openapi: 3.0.3

info:
  title: Export Management API
  version: 1.0.0
  description: OpenAPI for Export management

servers:
  - url: http://localhost:8080
    description: Local development server
  - url: http://3.7.63.123:8080
    description: Development Server
  - url: http://13.205.54.102:8080
    description: Production Server

tags:
  - name: Export
    description: Export Endpoints

security:
  - oauth2: [ ]
paths:
  /api/v1/invoice/{id}/type/{invoiceType}/pdf:
    get:
      tags:
        - Export
      operationId: getInvoicePdf
      summary: Get Invoice pdf
      description: Returns Invoice pdf
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: invoiceType
          in: path
          required: true
          description: The unique identifier of the invoice
          schema:
            $ref: '#/components/schemas/InvoiceType'
      responses:
        '200':
          description: PDF generated successfully
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/job-works/{id}/type/{jobWorkFormType}/png:
    get:
      tags:
        - Export
      operationId: getJobWorkPng
      summary: Get Job Work png
      description: Returns Job Work png
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: jobWorkFormType
          in: path
          required: true
          description: The variant of the job work form
          schema:
            $ref: '#/components/schemas/JobWorkFormType'
      responses:
        '200':
          description: PNG generated successfully
          content:
            image/png:
              schema:
                type: string
                format: binary
        '500':
          $ref: '#/components/responses/InternalServerError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '403':
          $ref: '#/components/responses/ForbiddenError'

  /api/v1/packing-invoices/{id}/pdf:
    get:
      tags:
        - Export
      operationId: getPackingInvoicePdf
      summary: Get packing invoice PDF by ID
      description: Returns a packing invoice PDF for a specific invoice ID, with all its items (cartoons) and a size summary table
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: PDF generated successfully
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'

components:
  securitySchemes:
    oauth2:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        code:
          type: string
        detail:
          type: object
    InvoiceType:
      type: string
      enum:
        - EXPORT
        - COMMERCIAL
        - PACKAGING_LIST
    JobWorkFormType:
      type: string
      enum:
        - AAVAK
        - JAVAK

  responses:
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFoundError:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'