<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.erp</groupId>
        <artifactId>SME-ERP</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>core-service-management</artifactId>
    <name>core-service-management</name>
    <description>core-service-management</description>
    <packaging>jar</packaging>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
        </dependency>
        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>7.4.0</version>
                <executions>
                    <execution>
                        <id>user-management-code-gen</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <skipValidateSpec>true</skipValidateSpec>
                            <inputSpec>${project.basedir}/src/main/resources/user-management.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>com.erp.api.usermanagement</apiPackage>
                            <modelPackage>com.erp.api.usermanagement.model</modelPackage>
                            <apiNameSuffix>UserManagementApi</apiNameSuffix>
                            <generateApiDocumentation>true</generateApiDocumentation>
                            <configOptions>
                                <openApiNullable>false</openApiNullable>
                                <interfaceOnly>true</interfaceOnly>
                                <library>spring-boot</library>
                                <useSpringBoot3>true</useSpringBoot3>
                                <delegatePattern>false</delegatePattern>
                                <disallowAdditionalPropertiesIfNotPresent>true
                                </disallowAdditionalPropertiesIfNotPresent>
                                <documentationProvider>none</documentationProvider>
                                <ensureUniqueParameters>true</ensureUniqueParameters>
                                <requestMappingMode>none</requestMappingMode>
                                <returnSuccessCode>true</returnSuccessCode>
                                <serializableModel>false</serializableModel>
                                <sortParamsByRequiredFlag>true</sortParamsByRequiredFlag>
                                <useOptional>true</useOptional>
                                <useResponseEntity>true</useResponseEntity>
                                <useSwaggerUI>false</useSwaggerUI>
                                <useTags>true</useTags>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>master-management-code-gen</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <skipValidateSpec>true</skipValidateSpec>
                            <inputSpec>${project.basedir}/src/main/resources/master.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>com.erp.api.mastermanagement</apiPackage>
                            <modelPackage>com.erp.api.mastermanagement.model</modelPackage>
                            <apiNameSuffix>MasterManagementApi</apiNameSuffix>
                            <generateApiDocumentation>true</generateApiDocumentation>
                            <configOptions>
                                <openApiNullable>false</openApiNullable>
                                <interfaceOnly>true</interfaceOnly>
                                <library>spring-boot</library>
                                <useSpringBoot3>true</useSpringBoot3>
                                <delegatePattern>false</delegatePattern>
                                <disallowAdditionalPropertiesIfNotPresent>true
                                </disallowAdditionalPropertiesIfNotPresent>
                                <documentationProvider>none</documentationProvider>
                                <ensureUniqueParameters>true</ensureUniqueParameters>
                                <requestMappingMode>none</requestMappingMode>
                                <returnSuccessCode>true</returnSuccessCode>
                                <serializableModel>false</serializableModel>
                                <sortParamsByRequiredFlag>true</sortParamsByRequiredFlag>
                                <useOptional>true</useOptional>
                                <useResponseEntity>true</useResponseEntity>
                                <useSwaggerUI>false</useSwaggerUI>
                                <useTags>true</useTags>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>invoice-management-code-gen</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <skipValidateSpec>true</skipValidateSpec>
                            <inputSpec>${project.basedir}/src/main/resources/invoice-management.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>com.erp.api.invoicemanagement</apiPackage>
                            <modelPackage>com.erp.api.invoicemanagement.model</modelPackage>
                            <apiNameSuffix>InvoiceManagementApi</apiNameSuffix>
                            <generateApiDocumentation>true</generateApiDocumentation>
                            <configOptions>
                                <openApiNullable>false</openApiNullable>
                                <interfaceOnly>true</interfaceOnly>
                                <library>spring-boot</library>
                                <useSpringBoot3>true</useSpringBoot3>
                                <delegatePattern>false</delegatePattern>
                                <disallowAdditionalPropertiesIfNotPresent>true
                                </disallowAdditionalPropertiesIfNotPresent>
                                <documentationProvider>none</documentationProvider>
                                <ensureUniqueParameters>true</ensureUniqueParameters>
                                <requestMappingMode>none</requestMappingMode>
                                <returnSuccessCode>true</returnSuccessCode>
                                <serializableModel>false</serializableModel>
                                <sortParamsByRequiredFlag>true</sortParamsByRequiredFlag>
                                <useOptional>true</useOptional>
                                <useResponseEntity>true</useResponseEntity>
                                <useSwaggerUI>false</useSwaggerUI>
                                <useTags>true</useTags>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>export-management-code-gen</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <skipValidateSpec>true</skipValidateSpec>
                            <inputSpec>${project.basedir}/src/main/resources/export-management.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>com.erp.api.exportmanagement</apiPackage>
                            <modelPackage>com.erp.api.exportmanagement.model</modelPackage>
                            <apiNameSuffix>ExportManagementApi</apiNameSuffix>
                            <generateApiDocumentation>true</generateApiDocumentation>
                            <configOptions>
                                <openApiNullable>false</openApiNullable>
                                <interfaceOnly>true</interfaceOnly>
                                <library>spring-boot</library>
                                <useSpringBoot3>true</useSpringBoot3>
                                <delegatePattern>false</delegatePattern>
                                <disallowAdditionalPropertiesIfNotPresent>true
                                </disallowAdditionalPropertiesIfNotPresent>
                                <documentationProvider>none</documentationProvider>
                                <ensureUniqueParameters>true</ensureUniqueParameters>
                                <requestMappingMode>none</requestMappingMode>
                                <returnSuccessCode>true</returnSuccessCode>
                                <serializableModel>false</serializableModel>
                                <sortParamsByRequiredFlag>true</sortParamsByRequiredFlag>
                                <useOptional>true</useOptional>
                                <useResponseEntity>true</useResponseEntity>
                                <useSwaggerUI>false</useSwaggerUI>
                                <useTags>true</useTags>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>item-management-code-gen</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <skipValidateSpec>true</skipValidateSpec>
                            <inputSpec>${project.basedir}/src/main/resources/item-management.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>com.erp.api.itemmanagement</apiPackage>
                            <modelPackage>com.erp.api.itemmanagement.model</modelPackage>
                            <apiNameSuffix>ItemManagementApi</apiNameSuffix>
                            <generateApiDocumentation>true</generateApiDocumentation>
                            <configOptions>
                                <openApiNullable>false</openApiNullable>
                                <interfaceOnly>true</interfaceOnly>
                                <library>spring-boot</library>
                                <useSpringBoot3>true</useSpringBoot3>
                                <delegatePattern>false</delegatePattern>
                                <disallowAdditionalPropertiesIfNotPresent>true
                                </disallowAdditionalPropertiesIfNotPresent>
                                <documentationProvider>none</documentationProvider>
                                <ensureUniqueParameters>true</ensureUniqueParameters>
                                <requestMappingMode>none</requestMappingMode>
                                <returnSuccessCode>true</returnSuccessCode>
                                <serializableModel>false</serializableModel>
                                <sortParamsByRequiredFlag>true</sortParamsByRequiredFlag>
                                <useOptional>true</useOptional>
                                <useResponseEntity>true</useResponseEntity>
                                <useSwaggerUI>false</useSwaggerUI>
                                <useTags>true</useTags>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>client-management-code-gen</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <skipValidateSpec>true</skipValidateSpec>
                            <inputSpec>${project.basedir}/src/main/resources/client-management.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>com.erp.api.clientmanagement</apiPackage>
                            <modelPackage>com.erp.api.clientmanagement.model</modelPackage>
                            <apiNameSuffix>ClientManagementApi</apiNameSuffix>
                            <generateApiDocumentation>true</generateApiDocumentation>
                            <configOptions>
                                <openApiNullable>false</openApiNullable>
                                <interfaceOnly>true</interfaceOnly>
                                <library>spring-boot</library>
                                <useSpringBoot3>true</useSpringBoot3>
                                <delegatePattern>false</delegatePattern>
                                <disallowAdditionalPropertiesIfNotPresent>true
                                </disallowAdditionalPropertiesIfNotPresent>
                                <documentationProvider>none</documentationProvider>
                                <ensureUniqueParameters>true</ensureUniqueParameters>
                                <requestMappingMode>none</requestMappingMode>
                                <returnSuccessCode>true</returnSuccessCode>
                                <serializableModel>false</serializableModel>
                                <sortParamsByRequiredFlag>true</sortParamsByRequiredFlag>
                                <useOptional>true</useOptional>
                                <useResponseEntity>true</useResponseEntity>
                                <useSwaggerUI>false</useSwaggerUI>
                                <useTags>true</useTags>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>order-management-code-gen</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <skipValidateSpec>true</skipValidateSpec>
                            <inputSpec>${project.basedir}/src/main/resources/order-management.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>com.erp.api.ordermanagement</apiPackage>
                            <modelPackage>com.erp.api.ordermanagement.model</modelPackage>
                            <apiNameSuffix>OrderManagementApi</apiNameSuffix>
                            <generateApiDocumentation>true</generateApiDocumentation>
                            <configOptions>
                                <openApiNullable>false</openApiNullable>
                                <interfaceOnly>true</interfaceOnly>
                                <library>spring-boot</library>
                                <useSpringBoot3>true</useSpringBoot3>
                                <delegatePattern>false</delegatePattern>
                                <disallowAdditionalPropertiesIfNotPresent>true
                                </disallowAdditionalPropertiesIfNotPresent>
                                <documentationProvider>none</documentationProvider>
                                <ensureUniqueParameters>true</ensureUniqueParameters>
                                <requestMappingMode>none</requestMappingMode>
                                <returnSuccessCode>true</returnSuccessCode>
                                <serializableModel>false</serializableModel>
                                <sortParamsByRequiredFlag>true</sortParamsByRequiredFlag>
                                <useOptional>true</useOptional>
                                <useResponseEntity>true</useResponseEntity>
                                <useSwaggerUI>false</useSwaggerUI>
                                <useTags>true</useTags>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>packing-invoice-management-code-gen</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <skipValidateSpec>true</skipValidateSpec>
                            <inputSpec>${project.basedir}/src/main/resources/packing-invoice-management.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>com.erp.api.packinginvoicemanagement</apiPackage>
                            <modelPackage>com.erp.api.packinginvoicemanagement.model</modelPackage>
                            <apiNameSuffix>PackingInvoiceManagementApi</apiNameSuffix>
                            <generateApiDocumentation>true</generateApiDocumentation>
                            <configOptions>
                                <openApiNullable>false</openApiNullable>
                                <interfaceOnly>true</interfaceOnly>
                                <library>spring-boot</library>
                                <useSpringBoot3>true</useSpringBoot3>
                                <delegatePattern>false</delegatePattern>
                                <disallowAdditionalPropertiesIfNotPresent>true
                                </disallowAdditionalPropertiesIfNotPresent>
                                <documentationProvider>none</documentationProvider>
                                <ensureUniqueParameters>true</ensureUniqueParameters>
                                <requestMappingMode>none</requestMappingMode>
                                <returnSuccessCode>true</returnSuccessCode>
                                <serializableModel>false</serializableModel>
                                <sortParamsByRequiredFlag>true</sortParamsByRequiredFlag>
                                <useOptional>true</useOptional>
                                <useResponseEntity>true</useResponseEntity>
                                <useSwaggerUI>false</useSwaggerUI>
                                <useTags>true</useTags>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>purchase-management-code-gen</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <skipValidateSpec>true</skipValidateSpec>
                            <inputSpec>${project.basedir}/src/main/resources/purchase-management.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>com.erp.api.purchasemanagement</apiPackage>
                            <modelPackage>com.erp.api.purchasemanagement.model</modelPackage>
                            <apiNameSuffix>PurchaseManagementApi</apiNameSuffix>
                            <generateApiDocumentation>true</generateApiDocumentation>
                            <configOptions>
                                <openApiNullable>false</openApiNullable>
                                <interfaceOnly>true</interfaceOnly>
                                <library>spring-boot</library>
                                <useSpringBoot3>true</useSpringBoot3>
                                <delegatePattern>false</delegatePattern>
                                <disallowAdditionalPropertiesIfNotPresent>true
                                </disallowAdditionalPropertiesIfNotPresent>
                                <documentationProvider>none</documentationProvider>
                                <ensureUniqueParameters>true</ensureUniqueParameters>
                                <requestMappingMode>none</requestMappingMode>
                                <returnSuccessCode>true</returnSuccessCode>
                                <serializableModel>false</serializableModel>
                                <sortParamsByRequiredFlag>true</sortParamsByRequiredFlag>
                                <useOptional>true</useOptional>
                                <useResponseEntity>true</useResponseEntity>
                                <useSwaggerUI>false</useSwaggerUI>
                                <useTags>true</useTags>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>sales-management-code-gen</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <skipValidateSpec>true</skipValidateSpec>
                            <inputSpec>${project.basedir}/src/main/resources/sales-management.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>com.erp.api.salesmanagement</apiPackage>
                            <modelPackage>com.erp.api.salesmanagement.model</modelPackage>
                            <apiNameSuffix>SalesManagementApi</apiNameSuffix>
                            <generateApiDocumentation>true</generateApiDocumentation>
                            <configOptions>
                                <openApiNullable>false</openApiNullable>
                                <interfaceOnly>true</interfaceOnly>
                                <library>spring-boot</library>
                                <useSpringBoot3>true</useSpringBoot3>
                                <delegatePattern>false</delegatePattern>
                                <disallowAdditionalPropertiesIfNotPresent>true
                                </disallowAdditionalPropertiesIfNotPresent>
                                <documentationProvider>none</documentationProvider>
                                <ensureUniqueParameters>true</ensureUniqueParameters>
                                <requestMappingMode>none</requestMappingMode>
                                <returnSuccessCode>true</returnSuccessCode>
                                <serializableModel>false</serializableModel>
                                <sortParamsByRequiredFlag>true</sortParamsByRequiredFlag>
                                <useOptional>true</useOptional>
                                <useResponseEntity>true</useResponseEntity>
                                <useSwaggerUI>false</useSwaggerUI>
                                <useTags>true</useTags>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- Compiler plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
